version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g gatsby --unsafe-perm=true --allow-root

  pre_build:
    commands:
      - echo Show working directory
      - ls
      - echo Installing source NPM dependencies.
      - npm install
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - aws s3 rm --recursive s3://${static-web}/public
      - aws s3 cp --recursive ./public s3://${static-web}/public
      - > 
        aws s3 cp 
        --cache-control="max-age=0, no-cache, no-store, must-revalidate"
        ./public/index.html s3://${static-web}/public
      - >
        aws cloudfront create-invalidation --distribution-id ${cf-distribution}
        --paths "/public"
artifacts:
  files:
    - '**/*'
  base-directory: public